package memoria;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author edcarlitosxd
 * Juan Carlos Uch Dzib
 */
public class Frame extends javax.swing.JFrame {

    int nivel, seg, aleatorio, aciertos, fallas;
    Image img1 = new ImageIcon(getClass().getResource("img/tachita.png")).getImage();
    Image img2 = new ImageIcon(getClass().getResource("img/palomita.jpeg")).getImage();
    ImageIcon palomita, tachita;
    public Timer tiempo;

    public ActionListener al = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent ae) {

            if (seg == 0) {
                genera();
            }
            if (seg == 3) {
                tiempo.stop();
                lblNumAlea.setText("");

            }
            seg++;
        }

    };

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        txtNumUser.setText("");
        nivel = 1;
        aciertos = 0;
        fallas = 0;
        tiempo = new Timer(1000, al);
        lblNivel.setText("Nivel: "+nivel);
        palomita = new ImageIcon(img2.getScaledInstance(acierto1.getWidth(), acierto1.getHeight(), Image.SCALE_SMOOTH));
        tachita = new ImageIcon(img1.getScaledInstance(acierto1.getWidth(), acierto1.getHeight(), Image.SCALE_SMOOTH));
    }

    public void genera() {
        Random n = new Random();
        Double aux = 1.0;

        switch (nivel) {
            case 1:
                aux = n.nextDouble() * 900 + 100;
                break;
            case 2:
                aux = n.nextDouble() * 9000 + 1000;
                break;
            case 3:
                aux = n.nextDouble() * 90000 + 10000;
                break;
            case 4:
                aux = n.nextDouble() * 900000 + 100000;
                break;
        }

        aleatorio = aux.intValue();
        lblNumAlea.setText(String.valueOf(aleatorio));

    }

    public void correcto() {
        switch (aciertos) {
            case 1:
                acierto1.setIcon(palomita);
                break;
            case 2:
                acierto2.setIcon(palomita);
                break;
            case 3:
                acierto3.setIcon(palomita);
                break;
            case 4:
                acierto4.setIcon(palomita);
                break;
            case 5:
                acierto5.setIcon(palomita);
                if (nivel < 7) {
                    reiniciarAciertos();
                    nivel++;
                    lblNivel.setText("Nivel: " + nivel);

                }
                reiniciarFallas();
                break;

        }

    }

    public void incorrecto() {

        switch (fallas) {
            case 1:
                falla1.setIcon(tachita);
                break;
            case 2:
                falla2.setIcon(tachita);
                break;
            case 3:
                falla3.setIcon(tachita);
                break;
            case 4:
                falla4.setIcon(tachita);
                break;
            case 5:
                falla5.setIcon(tachita);
                if (nivel > 1) {
                    reiniciarAciertos();
                    nivel--;
                    lblNivel.setText("Nivel: " + nivel);

                }
                reiniciarFallas();
                break;
        }

    }

    public void reiniciarAciertos() {
        aciertos = 0;
        acierto1.setIcon(null);
        acierto2.setIcon(null);
        acierto3.setIcon(null);
        acierto4.setIcon(null);
        acierto5.setIcon(null);
    }

    public void reiniciarFallas() {
        fallas = 0;
        falla1.setIcon(null);
        falla2.setIcon(null);
        falla3.setIcon(null);
        falla4.setIcon(null);
        falla5.setIcon(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lblNumAlea = new javax.swing.JLabel();
        txtNumUser = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        falla5 = new javax.swing.JLabel();
        falla1 = new javax.swing.JLabel();
        falla2 = new javax.swing.JLabel();
        falla3 = new javax.swing.JLabel();
        falla4 = new javax.swing.JLabel();
        acierto1 = new javax.swing.JLabel();
        acierto3 = new javax.swing.JLabel();
        acierto4 = new javax.swing.JLabel();
        acierto5 = new javax.swing.JLabel();
        acierto2 = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setText("MEJORA TU MEMORIA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 12, 216, 36);

        btnIniciar.setText("INICIAR");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        getContentPane().add(btnIniciar);
        btnIniciar.setBounds(150, 66, 216, 58);

        lblNumAlea.setText("99999999999");
        getContentPane().add(lblNumAlea);
        lblNumAlea.setBounds(170, 150, 128, 43);

        txtNumUser.setText("999999999");
        getContentPane().add(txtNumUser);
        txtNumUser.setBounds(170, 211, 122, 35);

        btnOK.setText("OK");
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOKMouseClicked(evt);
            }
        });
        getContentPane().add(btnOK);
        btnOK.setBounds(298, 211, 68, 35);

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Fallas"));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 310, 260, 150);

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Aciertos"));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 320, 240, 160);

        falla5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(falla5);
        falla5.setBounds(130, 400, 40, 50);

        falla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(falla1);
        falla1.setBounds(80, 330, 40, 50);

        falla2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(falla2);
        falla2.setBounds(140, 330, 40, 50);

        falla3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(falla3);
        falla3.setBounds(190, 330, 40, 50);

        falla4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(falla4);
        falla4.setBounds(80, 400, 40, 50);

        acierto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(acierto1);
        acierto1.setBounds(380, 330, 50, 60);

        acierto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(acierto3);
        acierto3.setBounds(440, 400, 50, 60);

        acierto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(acierto4);
        acierto4.setBounds(380, 400, 50, 60);

        acierto5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(acierto5);
        acierto5.setBounds(500, 330, 50, 60);

        acierto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(acierto2);
        acierto2.setBounds(440, 330, 50, 60);
        getContentPane().add(lblNivel);
        lblNivel.setBounds(410, 130, 80, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        // TODO add your handling code here:
        nivel = 1;
        lblNumAlea.setText("");
        tiempo.start();
    }//GEN-LAST:event_btnIniciarMouseClicked

    private void btnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseClicked
        int numuser = Integer.parseInt(txtNumUser.getText());
        if (aleatorio == numuser) {
            //Correcto
            aciertos++;
            correcto();

        } else {
            //Incorecto
            fallas++;
            reiniciarAciertos();

            incorrecto();
        }
        seg = 0;
        tiempo.start();
        txtNumUser.setText("");
    }//GEN-LAST:event_btnOKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acierto1;
    private javax.swing.JLabel acierto2;
    private javax.swing.JLabel acierto3;
    private javax.swing.JLabel acierto4;
    private javax.swing.JLabel acierto5;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel falla1;
    private javax.swing.JLabel falla2;
    private javax.swing.JLabel falla3;
    private javax.swing.JLabel falla4;
    private javax.swing.JLabel falla5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNumAlea;
    private javax.swing.JTextField txtNumUser;
    // End of variables declaration//GEN-END:variables
}
